name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_KEY: ${{ secrets.API_KEY }}
      # Add other environment variables as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: npm install  # Adjust based on your project setup
        
      - name: Code validation
        run: npm run lint  # Assuming you have linting configured
        
      - name: Build
        run: npm run build  # Adjust based on your project setup
        
      - name: Run unit tests
        run: npm test  # Assuming you have unit tests configured
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    
    env:
      SERVER_URL: ${{ secrets.SERVER_URL }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      # Add other environment variables as needed

    steps:
      - name: Deploy to production
        run: |
          # Add your deployment script here
          # Example: scp -r ./dist/* user@your-server:/var/www/html
